# Generated by Django 5.2.7 on 2025-10-16 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='dish name')),
                ('description', models.TextField(verbose_name='dish description')),
                ('ingredients', models.JSONField(default=list, verbose_name='ingredients')),
            ],
            options={
                'db_table': 'restaurant_dish',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated at')),
                ('dietary_preference', models.CharField(choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('non-vegetarian', 'non-vegetarian'), ('unknown', 'unknown')], default='unknown', max_length=64, verbose_name='dietary preference')),
                ('favorite_dishes', models.JSONField(default=list, verbose_name='favorite dishes')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant_customer',
            },
        ),
        migrations.CreateModel(
            name='DialogSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated at')),
                ('state', models.CharField(choices=[('init', 'init'), ('greeting', 'greeting'), ('day_reply', 'day reply'), ('ask_favorites', 'ask favorites'), ('favorites_reply', 'favorites reply'), ('ask_order', 'ask order'), ('order_reply', 'order reply'), ('analyze', 'analyze')], db_index=True, default='init', max_length=32, verbose_name='state')),
                ('messages', models.JSONField(default=list, verbose_name='messages')),
                ('analysis_result', models.JSONField(default=dict, verbose_name='analysis result')),
                ('customer_favorite_text', models.TextField(default='', verbose_name='customer favorite text')),
                ('customer_order_text', models.TextField(default='', verbose_name='customer order text')),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='restaurant.customerprofile')),
            ],
            options={
                'db_table': 'restaurant_conversation_session',
            },
        ),
    ]
